### ISSUE TITLE
# and ! as separators

### ISSUE THREAD

**Issue by SundareshSankaran** [sassoftware/sas-studio-custom-steps#20]
Need DIAP to also check for hash (#) and exclamation point (!) as possible separators automatically.

**Comment by stephanweigandt** [comment]
Created new pull request to address this issue!

**Comment by snlwih** [comment]
Pull request that addresses this issue is: #23 

 (TIP: GitHub markup supports [autolinked references to issues and pull requests](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls))

**Comment by snlwih** [comment]
Pull request has been merged
