### ISSUE TITLE
Separator not working accurately in some cases.

### ISSUE THREAD

**Issue by SundareshSankaran** [sassoftware/sas-studio-custom-steps#21]
Determination of separator not always accurate, especially when there are blanks in the variable name.

**Comment by snlwih** [comment]
Hi @stephanweigandt , 
This issue has been reported against your [DIAP entry](https://github.com/sassoftware/sas-studio-custom-steps/tree/main/Data%20Ingestion%20Auto%20Pilot%20DIAP%20Light%20for%20External%20Files). 
I think you were already working an adding this feature as well, right?

**Comment by stephanweigandt** [comment]
Created new pull request to address this issue!

**Comment by snlwih** [comment]
Pull request that addresses this issue is: #23 

 (TIP: GitHub markup supports [autolinked references to issues and pull requests](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls))

**Comment by snlwih** [comment]
Pull request has been merged
