### ISSUE TITLE
NLS chars not accurately dealt with

### ISSUE THREAD

**Issue by SundareshSankaran** [sassoftware/sas-studio-custom-steps#22]
NLS characters are not dealt with accurately, need to use k-functions.

**Comment by snlwih** [comment]
Hi @stephanweigandt , 
And this is another issue that has been reported against your [DIAP entry](https://github.com/sassoftware/sas-studio-custom-steps/tree/main/Data%20Ingestion%20Auto%20Pilot%20DIAP%20Light%20for%20External%20Files). 
I think you were already working an adding this feature as well, right?

**Comment by stephanweigandt** [comment]
Created new pull request to address this issue!

**Comment by snlwih** [comment]
Pull request that addresses this issue is: #23 

 (TIP: GitHub markup supports [autolinked references to issues and pull requests](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls))
