### ISSUE TITLE
Append Step help - Does it have support for multiple input tables?

### ISSUE THREAD

**Issue by vladsrynty** [sassoftware/sas-studio-custom-steps#35]
Is it possible to use Append Table step to append multiple source tables into one (big) output table? I see only one input port.

**Comment by snlwih** [comment]
Hi @vladsrynty,

You are correct that the current implementation of this custom step only supports one input port. So you would need to use the step twice, once for each input table, and have the output table show twice in the flow. See attached screenshot.

Some further clarification: Currently a Table step/node only supports a single input. That's the reason the table shows up twice in the flow. As this then results in multiple "streams" of nodes, the best practice approach is to put them in separate swimlanes. See attached screenshot.

Feel free to modify the custom step definition to support multiple input tables. This can be done by adding one (or more) input table controls in the Custom Step Designer, marking them as "not required" and then using the associated macro varaible in your SAS code. The user can then use the "Add Input Port" option on the node in the flow and attach a table to that port. Be aware that if the port has not been turned on by the user, the associated macro variable will not be generated by the custom step framework code generation and any references to that macro variable would result in warnings/errors at run time. So if the port was names inputTable2, then the SAS code should use %symexist(inputTable2) to check for the existence of the macro variable, and if the macro variable exists only then generate code that includes references &inputTable2.  Hope this helps.

@torbenjuul, you contributed this step. Any plans to add support for multiple input tables in your Append Table step?
![Screenshot Append Table and multiple source tables to append to single target table](https://user-images.githubusercontent.com/35299890/213401491-7d5098d9-0857-4318-97b3-7d4aef9f6020.png)

**Comment by snlwih** [comment]
Don't think the contributor has any short term plans to add support for multiple input tables. 

Closing this issue now as the question has been answered.
